/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package pl.com.boono.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventType { 
  SCAN, MONITORING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"pl.com.boono.avro\",\"symbols\":[\"SCAN\",\"MONITORING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
