/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package pl.com.boono.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SourceType { 
  APPLICATION, CLOUD_BEACON  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SourceType\",\"namespace\":\"pl.com.boono.avro\",\"symbols\":[\"APPLICATION\",\"CLOUD_BEACON\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
